Simulator:
  - changed-files:
      - any-glob-to-any-file: 'simulator/**/*'
Docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'

ExtensionLib:
  - changed-files:
      - any-glob-to-any-file: ['extensions/core/**/*', 'macros/src/ext/*', 'core/ext/*']

Macros:
  - changed-files:
      - any-glob-to-any-file: ['macros/**/*']

Extensions-Other:
  - changed-files:
    - any-glob-to-any-file: 'extensions/**/*'
    - all-globs-to-all-files: '!extensions/core/**/*'

Fuzzing:
  - changed-files:
      - any-glob-to-any-file: 'fuzz/**/*'

Perf/Benchmarks:
  - changed-files:
      - any-glob-to-any-file: ['perf/**/*', 'core/benches/*']

Go-Bindings:
  - changed-files:
    - any-glob-to-any-file: 'bindings/go/**/*'


WASM-Bindings:
  - changed-files:
    - any-glob-to-any-file: 'bindings/wasm/**/*'


Python-Bindings:
  - changed-files:
    - any-glob-to-any-file: 'bindings/python/**/*'

JS-Bindings:
  - changed-files:
    - any-glob-to-any-file: 'bindings/javascript/**/*'

Rust-Bindings:
  - changed-files:
    - any-glob-to-any-file: 'bindings/rust/**/*'

Java-Bindings:
  - changed-files:
    - any-glob-to-any-file: 'bindings/java/**/*'

Parser:
  - changed-files:
    - any-glob-to-any-file: "vendored/sqlite3-parser/*"

Cli:
  - changed-files:
    - any-glob-to-any-file: "cli/**/*"

Sqlite3:
  - changed-files:
    - any-glob-to-any-file: "sqlite3/**/*"

Core:
  - changed-files:
    - any-glob-to-any-file: 'core/**/*'

Optimizer:
  - changed-files:
    - any-glob-to-any-file: 'core/translate/optimizer/*'

Translation/Planning:
  - changed-files:
    - any-glob-to-any-file: 'core/translate/*.rs'

IO:
  - changed-files:
    - any-glob-to-any-file: 'core/io/*'

MVCC:
  - changed-files:
    - any-glob-to-any-file: 'core/mvcc/**/*'

VDBE:
  - changed-files:
    - any-glob-to-any-file: 'core/vdbe/*'

Json:
  - changed-files:
    - any-glob-to-any-file: 'core/json/*'

Storage:
  - changed-files:
    - any-glob-to-any-file: 'core/storage/*'

Vector:
  - changed-files:
    - any-glob-to-any-file: 'core/vector/*'

Antithesis:
  - changed-files:
    - any-glob-to-any-file: ['antithesis-tests/**/*', 'scripts/antithesis/*', 'stress/**/*']

CI-Actions:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/*.yml'
